### ISSUE TITLE
Satellite/Breakout session for HPC carpentry

### ISSUE THREAD

**Issue by fpsom** [carpentries/carpentrycon#24]
A satellite or breakout session at the CarpentryCon for the current/potential/interested users of HPC cluster, for use as the starting point to identify a target audience who could collaboratively develop lessons and teaching materials with Alan O'Cais.

Arguments for this:
•	As the demand for scientists compute resources grow, many will eventually need to use HPC resources as their workhorse. This is motivation behind https://github.com/swcarpentry/hpc-novice , where the current lesson addresses users of HPC facilities
•	Obviously many larger HPC sites already give an introduction to their own resources but many smaller sites could benefit from well-constructed, open source material
•	There is currently a gap in the HPC space for collaboratively developed, open source training material (and Software Carpentry can act as a lightning rod for those who do have material to contribute)
•	There is huge scope for lessons beyond a simple introduction on how to interact with resources, but the first step is do this part well and generate more interest/collaborators

**Comment by ocaisa** [comment]
Looking at [the potential agenda](https://github.com/carpentries/carpentrycon/blob/master/TopicsThemes.md) I imagine that there will be some competition for the breakout sessions, will there be a round for proposals?

Given the wide scope of SC, I wonder if an HPC breakout is a bit too niche? If a satellite event seems like a better option then I'd be happy to try to organise that since I already have a contact at UCD. I can hopefully recruit some help from [the HPC novice lesson](https://github.com/swcarpentry/hpc-novice) @psteinb and [MolSSI](https://github.com/MolSSI) @dgasmith to work on a program.

**Comment by psteinb** [comment]
very good idea. I am happy to support it whenever possible. Due to 
administrative reasons I can currently not promise my attendance though.

**Comment by dgasmith** [comment]
Happy to help out on this. Do let me know what I can do to move this forward.

**Comment by fpsom** [comment]
Thanks @ocaisa @psteinb @dgasmith ! Closing issue now after CarpentryCon 2018.
